### ISSUE TITLE
Operation Harsh Doorstep Supported Game

### ISSUE THREAD

**Issue by airmanparker34** [DiscordGSM/GameServerMonitor#30]
**Is your feature request related to a problem? Please describe.**
Operation Harsh Doorstep Supported Game request

**Describe the solution you'd like**
Requirements to support Operation:HarshDoorstep, AWN.gg hosted game for example

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by airmanparker34** [comment]
Game Port: 7777
Query Port: 27005

**Comment by BattlefieldDuck** [comment]
do you know the query method or any working game server online for testing? thanks

**Comment by xLeviNx** [comment]
added the request, pending pull

**Comment by xLeviNx** [comment]
> **Is your feature request related to a problem? Please describe.** Operation Harsh Doorstep Supported Game request
> 
> **Describe the solution you'd like** Requirements to support Operation:HarshDoorstep, AWN.gg hosted game for example
> 
> **Describe alternatives you've considered** N/A
> 
> **Additional context** Add any other context or screenshots about the feature request here.

Game has been added
