### ISSUE TITLE
Missing Permission: Send Messages

### ISSUE THREAD

**Issue by Kr3m** [DiscordGSM/GameServerMonitor#31]
If I go to delete and readd a server, I get Missing Permission: Send Messages.

The bot has received these permissions, so I'm not sure what is going on.  It was working until I went to delete a server so I could readd it.

**Comment by Kr3m** [comment]
```2023-02-17 11:06:13 ERROR    discordgsm Channel 1074424171607638136 send_message discord.Forbidden 403 Forbidden (error code: 50013): Missing Permissions```

**Comment by BattlefieldDuck** [comment]
Make sure your channel allows discordgsm send messages

**Comment by Kr3m** [comment]
> Make sure your channel allows discordgsm send messages

![image](https://user-images.githubusercontent.com/290740/219635333-4bb204a3-ebac-48b6-ae28-838a659b2261.png)

**Comment by BattlefieldDuck** [comment]
Not there, right click on your channel, and check your settings

**Comment by Kr3m** [comment]
> Not there, right click on your channel, and check your settings

That's literally from my server settings > integration.

**Comment by BattlefieldDuck** [comment]
Channel settings is different to server settings

**Comment by Kr3m** [comment]
> 

That fixed it.  Thank you very much.  I'm not sure why it was working before and then stopped, but it's all good now.  Cheers.
