### ISSUE TITLE
Alert message does not display `:lock:` emoji correctly

### ISSUE THREAD

**Issue by Elijahh177** [DiscordGSM/GameServerMonitor#36]
**Describe the bug**
The alert message title does display `:lock:` instead of :lock:.

**To Reproduce**
1. Add gameserver, which is password protected
2. Enable alert messages
3. Trigger an alert (e.g. restart server)
4. Observe alert message

**Expected behavior**
The 🔒 icon should be showed instead of `:lock:`.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/53260105/221353890-ff6b5a1e-5da8-4b80-a9b3-80cee46e86d2.png)

**Comment by BattlefieldDuck** [comment]
thanks for the bug report
