### ISSUE TITLE
Can't add UT2004 servers.

### ISSUE THREAD

**Issue by Kr3m** [DiscordGSM/GameServerMonitor#38]
**Describe the bug**
Can't add UT2004 servers.

**To Reproduce**
1. Add a UT2004 server.

**Expected behavior**
Should work fine, but I suspect it's a timeout issue if this relies on gamedig.

**Proposed solution**
Increase timeout time since it takes a little while for gamedig to query UT2004 servers.

**Server (please complete the following information):**
 - OS: Ubuntu 22.04

**Comment by xLeviNx** [comment]
Do you have an IP and port to test?

**Comment by Kr3m** [comment]
> Do you have an IP and port to test?

chi.kr3m.one:7777

**Comment by Kr3m** [comment]
DTGameServerMonitor
BOT
 — Today at 6:24 PM
Fail to query ut2004 server chi.kr3m.one:7777. Please try again.

**Comment by Kr3m** [comment]
I figured it out.  Seems that my query port changed when migrating the server.
