### ISSUE TITLE
Request to api.hellbz.de has changed

### ISSUE THREAD

**Issue by HellBz** [DiscordGSM/GameServerMonitor#44]
Hello Admin,

please set the User-Agent to my API-Request like the following 

https://api.hellbz.de//scum/api.php?address=176.57.181.82&port=28700

With a New Formated and validated User-Agent in this Format

Bot-Name/Version (Author-Name; Author-Website; Author-Contact Website or E-Mail; Additional Informations)

For example:
SCUM-List-Crawler/1.0 (HellBz; https://hellbz.de; cofing@hellbz.de; Some more you like to tell me..)

Best Regards,

Stefan aka HellBz

**Comment by BattlefieldDuck** [comment]
thanks for the reminder! We will solve it on the next release.
