### ISSUE TITLE
Additionnal game support

### ISSUE THREAD

**Issue by patrix87** [DiscordGSM/GameServerMonitor#53]
Would it be possible to add support for the following game:

- Ark Survival Ascended

Thanks

**Comment by xLeviNx** [comment]
> Would it be possible to add support for the following game:
> 
> * Ark Survival Ascended
> 
> Thanks

At the moment they utilize epic and there isn't an open means to query it. Unless its on steam query but don't see it happening anytime soon

**Comment by patrix87** [comment]
In the old version of [DiscordGSM](https://github.com/DiscordGSM/DiscordGSM) I added a way to add a custom server.
The objective was to as least show the server in the Discord channel.
The State of the server could be linked to a simple ping response on the IP of the server.
The Server information like map, max player, game, etc, were all manually entered.

I understand that represent a bit of work but it would be useful to many I think.

**Comment by dkoz** [comment]
> Would it be possible to add support for the following game:
> 
> * Ark Survival Ascended
> 
> Thanks

I've managed to add support for ASA on Discord GSM. I'll make a pull request when I'm done.

**Comment by BattlefieldDuck** [comment]
Ark Survival Ascended (asa) is supported since [2.15.0](https://github.com/DiscordGSM/GameServerMonitor/releases/tag/2.15.0). 👍
