### ISSUE TITLE
Not Queryable server

### ISSUE THREAD

**Issue by AjiBe52** [DiscordGSM/GameServerMonitor#60]
Can i force to add server, its randomly no queryable even my server online/running.
![Screenshot 2024-01-11 140110](https://github.com/DiscordGSM/GameServerMonitor/assets/156157217/ccb14d4d-5379-4bd2-8e61-e8e9f6c5042d)

**Comment by xLeviNx** [comment]
Elaborate on your question

**Comment by AjiBe52** [comment]
i cant add a minecraft server, its say not queryable, any help?

**Comment by AjiBe52** [comment]
of course, i can join to , bu its say no queryable

**Comment by dkoz** [comment]
> of course, i can join to , but its say no queryable

Check your `server.properties` and make sure the you have query enabled and a port forwarded for UDP.
```
enable-query=true
query.port=25565
```
