### ISSUE TITLE
Gportal server adding does not work

### ISSUE THREAD

**Issue by julianpoelmann** [DiscordGSM/GameServerMonitor#66]
**Describe the bug**
Simply using /addserver gportal and giving the information does not work. tried the quary port, game port and ftp port but it yields an error every time

i was trying to add my wreckfest server using this method

**To Reproduce**
1. try command
2. fill info
3. run
4. error

**Expected behavior**
my server being added

**Screenshots**
![afbeelding](https://github.com/DiscordGSM/GameServerMonitor/assets/28513665/06330b6d-d58d-438e-b9aa-f76786400909)

**Desktop (please complete the following information):**
 - Tiny11 Pro for workstations 22H2 build 22621.1194
 - Firefox nightly (not used)
 - 124.0a1 (2024-01-31) (64-bits)

**Smartphone (please complete the following information):**
 - OnePlus Open (not used)
 - OS: Coloros 13
 - Firefox Nightly

**Comment by Shiioriii** [comment]
that's not error, that's mean your server are not queryable

**Comment by julianpoelmann** [comment]
then what is the point of the gportal option? the quary port shouldnt matter as i had to use the regular port with my satisfactory server instead of the quary one. this is about wreckfest btw unless those servers dont support quary stuff and pinging

**Comment by BattlefieldDuck** [comment]
GPortal has a good API service, so we provided a way to query server with it.

Providing your server ip and port with gportal server id will be useful for troubleshooting this issue.
