### ISSUE TITLE
Palworld Server not more working

### ISSUE THREAD

**Issue by Blacky0316** [DiscordGSM/GameServerMonitor#82]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Blacky0316** [comment]
Palworld Nothing Running 

Query from palworld server ########## failed. Please try again.

But a different program doesn't work for them

**Comment by BattlefieldDuck** [comment]
Resolved the issue in 2.17.0
